### ISSUE TITLE
replace JS Map

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#102]
In 6/12/17 discussion about JS Map, we noticed that Map snuck into ExEx on 6/7/17 (after code review), and concluded that JS Map is not ready for use in PhET code.  It looks like Map is ExEx can be replaced with a string->value hash.

**Comment by samreid** [comment]
At least on of the Expression Exchange maps is using string keys.  It looks like another is using objects, so we will need another solution for that one.

**Comment by jbphet** [comment]
All usages of Map have been removed, closing.
