### ISSUE TITLE
game screen goes blank during fuzz testing

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#103]
When fuzz testing the latest version of the sim, the game screen seems to go blank after a short while.  Fuzz testing with just the game screen enabled makes this happen quite quickly.

**Comment by jbphet** [comment]
This was due to buttons being pressed while screens were being animated, so I made the screens non-interactive when they are moving.

**Comment by phet-steele** [comment]
fuzzed for ten minutes without the screen going blank, closing
