### ISSUE TITLE
X coin looks a little cut off in some situations

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#104]
Something about the artwork for the X coin has changed fairly recently, and it looks a bit cut off on the right side and the bottom in some situations.  Here is a screen capture from my secondary monitor that hopefully depicts the problem:
![exex-cut-off-coin](https://user-images.githubusercontent.com/3082831/27100241-9a3b9d8c-503a-11e7-8f69-2c3237968b30.PNG)

**Comment by jbphet** [comment]
When I look at the Adobe Illustrator file that contains the artwork for these coins, I notice that each coin has a little rectangle around it.  I'm not sure what this is (my skills with AI are pretty rudimentary), but I suspect it is involved in the cut-off appearance.  Assigning to @amanda-phet to see if she know what's going on.

**Comment by amanda-phet** [comment]
Each little rectangle is an artboard. Each coin gets exported based on that artboard, and yes that one might be a little too close to the edge of the coin, causing it to be cut off. I'll look in to each coin and re-export any others that might also be too close.

**Comment by amanda-phet** [comment]
@jbphet do you want to check to see if the coins look ok now? I visually verified each coin's .png and they all look good to me. In the sim they don't look as good, but that could potentially be caused by another issue.

**Comment by jbphet** [comment]
Yep, they look better now.  Thanks!  Closing.
