### ISSUE TITLE
Remove "Undo" buttons on completion of a level

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#107]
After conferring with @jbphet and @amanda-phet, we agree that the "Undo" buttons do not need to be visible once all three challenges have been answered correctly in a level. @jbphet, the buttons would disappear *immediately* after completion of a level, just as the Next button appears.

For phetsims/tasks/issues/860.

**Comment by jbphet** [comment]
I've added this functionality, will unassign and have it tested on next release.

**Comment by phet-steele** [comment]
Behaving amazingly in dev.4, woo!
