### ISSUE TITLE
Terms are lost off screen when dividing even number stacks

### ISSUE THREAD

**Issue by ayeemdee** [phetsims/expression-exchange#109]
One coin term gets stuck off screen when even number stacks are divided on the edge of the screen.

Start by being on a screen where terms can be placed on top of each other:
1. Create a stack of one term in even multiples
2. Move stack to edge of screen
3. Use scissors icon to divide stack
4. All but one of the cards returns to play area

![bug](https://user-images.githubusercontent.com/2342849/27157907-4819350e-5121-11e7-920c-dfaa05dbfac8.gif)

This doesn't happen with odd numbered stacks and it happens on all screens (excl. Home of course). It could be related to how the divide animation works when stacks are close to the edge of the screen. 
Tested this on Windows 10 Chrome and iPad Air 2 Safari and it occurs on both.

For phetsims/tasks#860

Troubleshooting information (do not edit):
Name: ‪Expression Exchange‬
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.1.0-dev.3/expression-exchange_en.html
Version: 1.1.0-dev.3 2017-06-13 18:51:38 UTC
Features missing: generatedcontent
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Language: en-US
Window: 1536x774
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"045bd1b0","branch":"master"},"babel":{"sha":"6d9fa297","branch":"master"},"brand":{"sha":"c904b097","branch":"master"},"chipper":{"sha":"80ae1f14","branch":"master"},"dot":{"sha":"6b4ec39c","branch":"master"},"expression-exchange":{"sha":"5d9ee7b4","branch":"master"},"joist":{"sha":"b35547e9","branch":"master"},"kite":{"sha":"7d2df183","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"ca2f62cd","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"c2248424","branch":"master"},"scenery-phet":{"sha":"01067d19","branch":"master"},"sherpa":{"sha":"812fdf9e","branch":"master"},"sun":{"sha":"32cc2197","branch":"master"},"tandem":{"sha":"7b8b8188","branch":"master"},"vegas":{"sha":"45acc1de","branch":"master"},"vibe":{"sha":"5e8151e1","branch":"master"}}

**Comment by phet-steele** [comment]
Looks fixed in dev.4.
