### ISSUE TITLE
Why do collection areas still have a green halo when they already contain an answer?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#111]
If we use the green halo to cue "hey, try to check your answer here", then it doesn't make sense to show the green halo when the collection area already contains an answer. You can't answer the same challenge twice. I'd say if a collection area already has an answer, don't show the green halo on hover.

![ee14](https://user-images.githubusercontent.com/5863899/27196774-119c0486-51c9-11e7-9a70-0b4f1e1af1e7.gif)

For phetsims/tasks/issues/860.

**Comment by amanda-phet** [comment]
Makes sense to me.

**Comment by jbphet** [comment]
Fixed, leaving open and will have this verified in next release.

**Comment by phet-steele** [comment]
Looks good in dev.4, thanks y'all.
