### ISSUE TITLE
@public {Type} (read-only) should be changed to @public (read-only) {Type}

### ISSUE THREAD

**Issue by samreid** [phetsims/expression-exchange#116]
I noticed that in Expression Exchange the visibility annotation parentheticals are after the types, but nearly everywhere else (the exception being one file in Proportion Playground) the visibility (and read-only) are provided before the type.

For instance, Expression Exchange has lines like:
```js
// @public {ObservableArray.<Vector2>} (read-only) - the points where the ball has collided with the walls
```

While other sims use this pattern (example from Function Builder)
```js
// @public (read-only) {Property.<Vector2>} DO NOT set this directly! Use moveTo or animateTo.
```

I can see the advantages of both approaches but it seems more important to me to be consistent.

**Comment by jbphet** [comment]
Done.  @samreid - you can take a look and see if these appears to meet the standards or simply close at your discretion.

**Comment by samreid** [comment]
Looks great, thanks!  I noticed a few spots where parentheses were missing or where the parens came before the `@`.  Everything else is great.

```js
// @public, read only, values that describe the nature of this coin term
...
// @public, read only, indicates that the value will never change, will be displayed differently in the view
...
// @public, listen only, a property which contains the text that should be shown when displaying term value
...
this.heightProperty = new Property( 0 ); // (read-only) @public {Property.<number>}

**Comment by jbphet** [comment]
Stragglers cleaned up.  I think that should do it - closing.
