### ISSUE TITLE
Term jump needs to be bounded

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#117]
You can continually touch a term until it goes up above the screen:

![ee18](https://user-images.githubusercontent.com/5863899/27455094-6cda1712-5759-11e7-87ae-3a6e9307588b.gif)

Seen on iPad Air 2 iOS 10.3.2. For phetsims/tasks/issues/860.

**Comment by jbphet** [comment]
Should now be bounded, please verify on master.

**Comment by phet-steele** [comment]
Good in dev.4!
