### ISSUE TITLE
screen names use incorrect format

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#126]
The naming convention for screen names was not adhered to in the strings file.  This might be because the convention was a little unclear in the code review checklist, but @pixelzoom recently made an update that clarified it, see https://github.com/phetsims/phet-info/commit/e66474483fb5a1891ca8975f4a064bbb6dcd68ac.

This should be fixed, but doing so is a little tricky since there are 16 translations as of this writing.  I think the steps to do this would be:
+ Take Rosetta off line
+ Change the string keys in the `strings_en.json` file on master
+ Change the string keys in all of the translations
+ Cherry pick the string file commit into the release branch, do a maintenance release
+ Verify that the English sim was built correctly and contains the new string keys
+ Verify that all of the translations were rebuilt
+ Spot check several of the translated versions and verify that the new string keys were used
+ Put Rosetta back on line
+ Spot check several translations in the Rosetta interface to make sure that the previous screen names are appearing with the new keys

**Comment by pixelzoom** [comment]
> The naming convention for screen names was not adhered to in the strings file.

Given the amount of work required here, I would just live with it.  I'm sure this isn't the only sim that doesn't follow the convention.  My 2 cents...

**Comment by jbphet** [comment]
Okay, living with it.  Closing.
