### ISSUE TITLE
assertion failure in AbstractCoinTermNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#129]
While working on another issue, I ran across this.   

Running from master with `?ea&fuzzMouse`,  I see the following assertion failure:

```js
window.assertions.assertFunction (assert.js:22)
hideBreakApartButton (AbstractCoinTermNode.js?bust=1505928743681:207)
(anonymous) (AbstractCoinTermNode.js?bust=1505928743681:180)
callback (Timer.js?bust=1505928743681:46)
step (Timer.js?bust=1505928743681:32)
stepSimulation (Sim.js?bust=1505928743681:835)
runAnimationLoop (Sim.js?bust=1505928743681:779)
requestAnimationFrame (async)
```

with message:

> Assertion failed: break apart button bounds are empty, this.breakApartButton.bounds =

**Comment by phet-steele** [comment]
@pixelzoom, see the immediately preceding issue, #127. Closing as duplicate (reopen if I'm mistaken)

**Comment by pixelzoom** [comment]
Sorry about that. I did look at open issues, but the title of #127 indicated a different assertion.  I see that in later comments the AbstractCoinTermNode was identified, guess it's related somehow.
