### ISSUE TITLE
usability of dragging with touch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#133]
Noticed while working on reusing the "halo" and "sum to zero" behavior in equality-explorer, see https://github.com/phetsims/equality-explorer/issues/17.

While dragging things around (x,-x,1,-1,...) on iPad, I find it frustrating that I can't see what I'm dragging, because it's always directly under my finger.   Also makes it more difficult to place things, and to see some of the visual cues for assembling things in the play area.  It would be a lot more usable if what you're dragging what a bit above your finger.

**Comment by amanda-phet** [comment]
Hm, we added a vertical jump to the object when using it on a touch device and tested it out to see if there was still occlusion, so I'm surprised you are still finding the object directly under your finger. 

I don't have time to look at this right now, but perhaps @phet-steele can take a look (or assign an undergrad) and see what is going on?

**Comment by pixelzoom** [comment]
I'm using the version published on the PhET website.  On pointer down, I do see the Node move up, but not enough that I can see more than the top 1/2 of it.  I have relatively small finger tips.

**Comment by phet-steele** [comment]
The jump-distance was refined in https://github.com/phetsims/expression-exchange/issues/112 and should not be changed so that issue doesn't occur again.

Additionally, I have zero problems with occlusion. The terms are quite far above my finger.
