### ISSUE TITLE
'grunt published-README' was not run in release branches

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#134]
All of the release branches for this sim still indicate that the sim is unpublished.

The master checklist for sims says:

> - [ ] README.md updated using `grunt published-README` (in master and release branch)

**Comment by pixelzoom** [comment]
This appears to be a problem with `grunt production`.  It runs `grunt published-README` in master, but not in the release branch.

**Comment by jbphet** [comment]
I updated the README.md on this branch by cherry picking the original commit that created it on master, see 41f6df483c44b81b2e378e2936dc682aa5529837.  The README.md now looks correct on the 1.1 branch, closing.

**Comment by jbphet** [comment]
By the way, I did NOT update the README.md on the 1.0-phetio branch, since that was a pre-release version that was used for some testing, so it seemed inappropriate for the README.md to indicate that it was a fully published sim.
