### ISSUE TITLE
evaluate stepper option to Carousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#136]
Carousel was converted to use TWIXT/Animation in https://github.com/phetsims/sun/issues/381.  The default is `stepper: 'manual'`, which means that the client must call `step` to control the Carousel's animation.   To avoid having to make changes in this sim, `stepper: 'timer'` was added to Carousel call sites, which means that the animation will run automatically using the sim Timer.  

The responsible developer should evaluate what `stepper` value should be used.

**Comment by jbphet** [comment]
I've reviewed the change, and have decided to leave it as is, i.e. using the `stepper: 'timer'` option.  This node is not currently being stepped in the implementation and I don't see much value in changing this, so I'll leave it as it was, where the animation behavior was autonomous.  Closing.
