### ISSUE TITLE
remove Tween preload?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#140]
I don't see TWEEN used anywhere in expression-exchange or its dependencies, but I see this preload in package.json:

```js
    "preload": [
      "../sherpa/lib/Tween-r12.js"
    ]
```

Can this preload be removed?

**Comment by jbphet** [comment]
Yes indeed, it can be.  I've removed it and regenerated the HTML, and also removed a comment that referenced TWEEN and was no longer correct.  I must've missed this items when working on #137, so it's good this was caught.  I'm just going to close this issue, but @pixelzoom you're welcome to review if you think it's necessary when you see the GitHub notification go by.

**Comment by jbphet** [comment]
BTW, I tested both the RequireJS and built versions after making the changes described above.
