### ISSUE TITLE
Dealing with dynamically selected mipmap vs image

### ISSUE THREAD

**Issue by samreid** [phetsims/expression-exchange#143]
Related to https://github.com/phetsims/expression-exchange/issues/91 and discovered during https://github.com/phetsims/chipper/issues/874 and tagging for work during https://github.com/phetsims/chipper/issues/850

Elevating priority so we can determine if this is necessary before the migration.  Marking blocks sim publication so we can make sure to decide on this issue before next sim publication.

The migration steps don't currently support the dynamic selection of plugin in `CoinNodeFactory`:

```js
  // images - use mipmaps normally, but use regular images when memory needs to be conserved
  const useMipmaps = !platform.mobileSafari;

  let coinXBackImage;
  // ...

  if ( useMipmaps ) {
    coinXBackImage = require( 'mipmap!EXPRESSION_EXCHANGE/coin-x-back.png' );
    // ..
  }
  else {
    coinXBackImage = require( 'image!EXPRESSION_EXCHANGE/coin-x-back.png' );
    // ...
  }
```

I'd like to apply a workaround to get this sim running in ES6 modules for now.  Some choices:
(a) just use mipmaps for everything, now that we no longer support iPad2 this may be OK
(b) just use images for everything, it is unclear that the mipmaps make any rendering difference in our currently supported browsers, see https://github.com/phetsims/chipper/issues/840.  This would reduce memory usage and download size.
(c) load both types statically with import statements (not in an if statement) and then select which one to render with an if statement.  This would take even more memory.
(d) change our ES6 module migration and tooling to support this use case.

I'm inclined to go with (a) or (b) because they are a bit easier.  I can test (b) myself on a few browsers, so perhaps we'll start with that, but we can change if necessary.

**Comment by samreid** [comment]
Just `image!` looked OK on my mac Chrome, Safari and Firefox, so I'll start with that.

**Comment by jbphet** [comment]
Looks okay to me too on Chrome on my main screen and spare monitor, and on Firefox on my main screen.  I also took a quick look at the history of the file to see if there were any obvious commits related to issues reported about image resolution, and I didn't see any.  Let's go with it.  Closing.
