### ISSUE TITLE
generalize numeric spinner

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#2]
In https://github.com/phetsims/sun/issues/85 (numeric spinner), @ariel-phet wrote:

> Assigning to @jbphet to look at when he works on Expression Exchange.

Assign this issue to @jbphet so that it's included in the work estimate for expression-exchange.

**Comment by jbphet** [comment]
@pixelzoom and @andrea-phet took care of generalizing the number spinner, closing.
