### ISSUE TITLE
create artwork for home screen and nav bar icons

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#24]
The sim is currently auto generating random icons.  Since we're about to publish a dev version that will be used for designing activities, it would be good to put "real" icons in the sim.

**Comment by jbphet** [comment]
Assigning to @ariel-phet initially, since I'm not sure if @amanda-phet will be available to work on this.

**Comment by ariel-phet** [comment]
@amanda-phet I don't think there is a huge rush on these icons, but obviously will need to be done before publication

**Comment by jbphet** [comment]
I've implemented a set of icons based on what @amanda-phet put in the design doc.  These can be seen in this version: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.14/expression-exchange_en.html.  @amanda-phet should review and, if these look like they'll do the trick, close the issue.

**Comment by amanda-phet** [comment]
Just one minor request: On the Variables screen icon, the subtraction sign should be a little larger to match what the sim would look like.

![screen shot 2016-07-21 at 10 04 39 am](https://cloud.githubusercontent.com/assets/7852916/17029957/a1d64536-4f2a-11e6-81d8-b7d3234a5a57.png)

**Comment by jbphet** [comment]
I changed the subtraction sign to use the Unicode character and the text font (as opposed to the math font), and it looks good.  Closing.
