### ISSUE TITLE
Parentheses around squared negative variables

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#25]
@amanda-phet should we consider adding parentheses around all instances of the squared negative terms? Students certainly have trouble understanding the order of operations here, and don't know if this should be 4 or -4:
<img width="113" alt="screen shot 2016-06-13 at 10 45 43 am" src="https://cloud.githubusercontent.com/assets/5863899/16015659/06cfbd72-3154-11e6-8bba-6653cac746f2.png">

Enabling "All Coefficients" or having a non-one coefficient does however present parentheses:
<img width="148" alt="screen shot 2016-06-13 at 10 45 51 am" src="https://cloud.githubusercontent.com/assets/5863899/16015667/0e495982-3154-11e6-9d87-9545242049b5.png">

**Comment by amanda-phet** [comment]
>Students certainly have trouble understanding the order of operations here, and don't know if this should be 4 or -4:
screen shot 2016-06-13 at 10 45 43 am 

You are indeed correct, which is why we have designed this sim in this way! We want students to see the term in this way so that they learn how to interpret it when they come across it later.

**Comment by phet-steele** [comment]
@amanda-phet, right-o! Kudos to the design team.
