### ISSUE TITLE
[iOS] Text Artifacts

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#26]
Dragging a variable term around leaves these behind; this trail was from the x2y2 term:
![img_0046](https://cloud.githubusercontent.com/assets/5863899/16280075/1df7dc22-387b-11e6-8106-6c957b959363.PNG)

**Comment by phet-steele** [comment]
Also being seen on macOS 10.12.1 Safari 10.

**Comment by jbphet** [comment]
We are getting close to releasing this sim, and a lot has changed.  Assigning to @phet-steele to determine if this is still an issue and, if so, I'll add an invisible backing rectangle that should prevent the problem.

**Comment by phet-steele** [comment]
@jbphet, still an issue in current master.

**Comment by jbphet** [comment]
I've handled this using "the usual method", which is to add a transparent rectangle that is equal to the expanded bounds of the text.  I tested it on an iPad 2 (the PhET iPad named "Tycho") and it seemed to resolve the issue.  Please verify on master.

**Comment by phet-steele** [comment]
I don't see them on Tycho + dev.4 anymore!
