### ISSUE TITLE
Can't break apart negatives on the Variables screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#28]
😭

**Comment by phet-steele** [comment]
Nor the constant terms.

**Comment by jbphet** [comment]
The design team decided that, at least for now, it shouldn't be possible to break apart constants.  In the June 9 meeting notes in the design doc it says, "...no edit/break apart on just a constant".

**Comment by jbphet** [comment]
Fixed for negatives, closing.
