### ISSUE TITLE
coin terms can be redundantly added to an expression during fuzz testing

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#31]
Fuzz testing revealed an issue where coin terms can sometimes be added back to an expression where they already reside.  This ends up hitting and assertion.  I spent several hours looking for the root cause but wasn't able to figure it out, and have decided to table it for now, since it is unlikely to impact users.  I added a simple workaround that just skips the add if the coin term is already part of the expression.  This is in the Expression.addCoinTerm method and is marked with TODO.

**Comment by jbphet** [comment]
This may have been fixed, or at least improved, by https://github.com/phetsims/expression-exchange/commit/7777165a96e4f26be4b701523283fa49f3c241f0.

**Comment by jbphet** [comment]
Nope, not fixed, at least not entirely.  The fuzz testing seemed to go longer (well over 10 minutes in one test), but eventually did hit the issue where coin terms were being added back to the same expression.

**Comment by jbphet** [comment]
One of the cases in which this problem can arise is if the mouse or touch bounds of the coin terms are set up such that the protrude from beyond the edges of the expression in which they are contained, and the user (or the fuzz test) grabs the coin term via these protruding bounds and then drops the coin term back into the expression.  I've adjusted the expression size to prevent this from happening, but future maintainers should be aware of this.

I'm currently investigating ways to disable coin term interaction completely when in an expression and not in edit mode.

**Comment by jbphet** [comment]
I ended up adding a new property to coin terms that can be used to explicitly disable user interaction, and the code now sets this 'prevent interaction' flag whenever coin terms are in expressions (this turned out to be useful for resolving another issue as well, see #64).  This should prevent problems even if the mouse/touch areas of the coin term peek out from inside the expression.

**Comment by jbphet** [comment]
Unassigning, will have this verified on next dev or rc release.

**Comment by phet-steele** [comment]
@jbphet took me three hours of fuzzing:

```
Uncaught Error: Assertion failed: coin term is already present in expression
    at window.assertions.assertFunction (assert.js:21)
    at Expression.addCoinTerm (Expression.js?bust=1497557106320:416)
    at ExpressionManipulationModel.js?bust=1497557106320:914
    at Array.forEach (<anonymous>)
    at Array.destinationReachedListener (ExpressionManipulationModel.js?bust=1497557106320:910)
    at Emitter.emit (Emitter.js?bust=1497557106320:114)
    at Expression.step (Expression.js?bust=1497557106320:300)
    at ExpressionManipulationModel.js?bust=1497557106320:341
    at Array.forEach (<anonymous>)
    at ObservableArray.forEach (ObservableArray.js?bust=1497557106320:306)
```

**Comment by jbphet** [comment]
Recent changes to #64 and #113 may have addressed this, and I was able to run several hours of fuzz testing without hitting it.  Assigning to @phet-steele to test on dev or RC version.

**Comment by phet-steele** [comment]
2 hours today, no issues.
