### ISSUE TITLE
Terms fail to be removed from the model

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#35]
Certain terms in an expression will not correctly return to the carousel if their node does not overlap with the carousel. They will animate towards the correct destination, but then not leave the play area and will be hovering over the carousel. Terms will remain in the My Collection panel to reflect this.

In each of the below conditions, follow the order of terms in the expression explicitly. Additionally, each expression was dropped into the carousel by releasing here, just when the left edge of the expression touches the right edge of the carousel:
![termsremain](https://cloud.githubusercontent.com/assets/5863899/17005719/e5b38f44-4e98-11e6-8b20-d649a468fa2c.png)

@jbphet good luck. There's a point in the table where I say "pre-made" and (x & x). This is how I distinguish between using the 2x term that exists on the second page of the carousel (pre-made) and using two single x terms and combining them to make 2x (x & x):

| Starting Expression | Remaining Terms |
| --- | ---|
| x + x | x |
| y + y | none |
| x + x + x | x, x |
| y + y + y | none |
| x + y | none |
| y + x | x |
| x + x + y | x |
| y + x + x | x, x |
| x + x + y + y | x |
| x + x + x + y | x, x |
| x + x + x + y +y | x, x |
| x + x + y + y + x | x, x |
| 2x(pre-made) + 2x(pre-made) | none |
| 2x(x & x) + 2x(x & x) | x, x |
| y + y + y + x + x + x + x + x^2 + y^2 + x^2y^2 | x, x, x, x |
| y + y + y + x + x + x + x + x + x^2 + y^2 + x^2y^2 | x, x, x, x, x, x^2 |
| y + y + y + x + x + x + x + x + x + x^2 + y^2 + x^2y^2 | x, x, x, x, x, x, x^2, y^2 |
| y + y + y + x + x + x + x + x + x + x + x^2 + y^2 + x^2y^2 | x, x, x, x, x, x, x, x^2, y^2, x^2y^2 |
| x + x + x + x + x + x + x + x^2 + y^2 + x^2y^2 | x, x, x, x, x, x |

**Comment by jbphet** [comment]
I am kind of able to duplicate this on http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.14/expression-exchange_en.html.  It's not as easy to recreate as described above, but I was able to get some terms left over (evidenced by the fact that they didn't disappear from the "My Collection" display box) if I went to the first screen and created an expression with all the available x, y, and z terms - 21 in total - and then dragged it to the left side of the carousel and released it.  Generally, there would be several z terms leftover.

The exact same procedure on the current master version does not leave any leftover terms, so I'm going to assign this back to @phet-steele to see if he can reproduce.  If so, please provide detailed instructions.  If not, please close.

**Comment by phet-steele** [comment]
@jbphet, easily reproduced on master (working as of 2:42 PM 9/29) with an expression of all 8 x^2 terms (variables or coins).
