### ISSUE TITLE
LeftRightNumberSpinner issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#36]
Issues noted while reviewing this implementation for https://github.com/phetsims/sun/issues/85.

(1) It's not just a spinner

... it also includes a very specific label and equals sign to the left of the spinner, e.g. "x =".  So I'm not going to attempt to  generalize this, and it will up to @jbphet to incorporate the spinner that's being generalized in https://github.com/phetsims/sun/issues/85.

(2) Equals sign

``69  new Text( '=', { font: EQUALS_SIGN_FONT } ),```

In function-builder, I was asked to use the Unicode symbol for equals (`'\u003d'`). No idea if this would look different for English, but it might for other locales.  In general, I think it's a good idea to use Unicode for mathematical symbols.
 
(3) Vestigial reference to "tweak" 

In https://github.com/phetsims/sun/issues/85#issuecomment-234602668, @jbphet wrote:
>  I had forgotten that this UI element is referred to as a "spinner" and had called it a "tweaker", which is probably why @pixelzoom was unable to find it. I've renamed it to LeftRightNumberSpinner

The documentation still refers to "tweak":

```* control that allows the user to adjust, a.k.a. 'tweak', the value of a variable```

**Comment by pixelzoom** [comment]
Now that sun.NumberSpinner has been generalized (see https://github.com/phetsims/sun/issues/85), expression-exchange should use it.

**Comment by jbphet** [comment]
The new NumberSpinner has been integrated and is lookin' good.  Closing.
