### ISSUE TITLE
Have a hint on both terms when adding to an existing expression?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#47]
@amanda-phet take the following into consideration:

When combining terms, both the user controlled (moving) coin and the coin in the play area (anchor) receive a yellow halo. This makes it very obvious exactly which coins will end up combining (moving is the middle coin):

<img width="215" alt="screen shot 2016-11-16 at 2 50 11 pm" src="https://cloud.githubusercontent.com/assets/5863899/20367492/fd4f5cc4-ac0c-11e6-89cd-28a3af7bff08.png">

When creating an expression, it's the anchor term that receives an expression halo. This makes it very obvious exactly which coins will end up making an expression (moving is the middle coin):

<img width="344" alt="screen shot 2016-11-16 at 2 53 40 pm" src="https://cloud.githubusercontent.com/assets/5863899/20367499/03f8a850-ac0d-11e6-953f-c9eb5e1c2fc8.png">

However! When adding terms to an existing expression, only the expression (regardless of if it is moving or the anchor) receives a hint. This does not address the confusion of which of these will be added to the expression (moving is the existing expression):

<img width="414" alt="screen shot 2016-11-16 at 2 56 35 pm" src="https://cloud.githubusercontent.com/assets/5863899/20367511/10725ec8-ac0d-11e6-8370-e3207d851415.png">

Wouldn't it be better to stay consistent and add a hint that clarifies exactly what term is being added? Maybe something like this:

<img width="580" alt="screen shot 2016-11-16 at 2 59 43 pm" src="https://cloud.githubusercontent.com/assets/5863899/20367827/6afd2e6c-ac0e-11e6-8e84-612116dd8b46.png">

or this:

<img width="756" alt="screen shot 2016-11-16 at 3 10 29 pm" src="https://cloud.githubusercontent.com/assets/5863899/20368047/8d406c9a-ac0f-11e6-908c-1b9576ff421b.png">

or this:

<img width="478" alt="screen shot 2016-11-16 at 3 10 38 pm" src="https://cloud.githubusercontent.com/assets/5863899/20368196/3798a716-ac10-11e6-9366-a3457aebe70f.png">

or...you get the point.

**Comment by jbphet** [comment]
@phet-steele and I discussed this a bit.  I don't object to the idea, but it wouldn't be an easy change to make at this point in the development because the hints are associated with the expression, not the coin-term that is about to join the expression.  It could definitely be done, but it seems like a bit of a rare case, and in my opinion the current behavior is not particularly confusing, so I would request that @amanda-phet consider the cost/benefit ratio when deciding if this feature should be implemented.

**Comment by amanda-phet** [comment]
Thanks for the thoughtful suggestion. Let's see what happens in interviews, but cost is an important factor, especially at this stage in the sim development.

**Comment by amanda-phet** [comment]
I haven't seen issues with this particular interaction in interviews so I think we can leave the sim as-is.
