### ISSUE TITLE
Change order of carousel items on Variables screen

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/expression-exchange#48]
I noticed in interviews that students were excited to play with negative terms, so I think it would be nice to have them be more visible on the Variables screen. Another reason to rearrange the carousel items is to have terms that "cancel" next to each other, to make it more likely that a student will discover what happens when you combine two opposites (such as x and -x). It is annoying to swipe through the carousel in order to pull out two opposites, and this learning goal seems to be more important than playing with x^2 (that term already existed on the previous screen). 

Please rearrange the terms so that they are listed as {x, -x, 1, -1, x^2, -x^2, y, -y}

**Comment by jbphet** [comment]
Done, closing.
