### ISSUE TITLE
Can/should there be common code to support card stacks?

### ISSUE THREAD

**Issue by samreid** [phetsims/expression-exchange#49]
We have other simulations with card stacks?  Can this code be generalized, or must it be re-implemented for each sim with card stacks?  What about the model element creator patterns?  @pixelzoom avoided model element creator pattern in Function Builder.  See also Area Builder, Fractions Intro, etc.

**Comment by pixelzoom** [comment]
We have discussed "creator" pattern in https://github.com/phetsims/scenery-phet/issues/214.  Smelly code identified in https://github.com/phetsims/scenery-phet/issues/214#issuecomment-174014179.

**Comment by samreid** [comment]
@jbphet and I discussed this on Friday.  Build a Fraction has card stacks but also shape stacks. It seems unlikely that the shape stacks would be able to reuse much code.  It also seemed unlikely that expression exchange would be able to share code with build a fraction, unless it was heavily refactored.

@jbphet anything else to add for this issue?

**Comment by jbphet** [comment]
I added some documentation to `CoinTermCreatorNode` about how it might be generalized in the future.  Even though @pixelzoom feels like there is some "smelly code" in other instances of the creator node pattern, I still feel it has potential for generalization.

Another thing to note is that one of the big differences between how Build a Fraction and Expression Exchange operate is that the former pre-allocates the model elements and puts them in the toolbox, whereas the latter creates the model elements on demand using 'creator nodes'.  Neither of these approaches is inherently superior IMO - it just depends on the particular application.  We may add support for generalizing either or both patterns in the future.

I think that's about it.  Closing.

**Comment by pixelzoom** [comment]
@jbphet said:
> Even though @pixelzoom feels like there is some "smelly code" in other instances of the creator node pattern,

If you read https://github.com/phetsims/scenery-phet/issues/214#issuecomment-174014179, you'll see that @jonathanolson identified the code in question.  I was just reporting that here (though I happen to agree with him about "smell"). Other issues were also reported in https://github.com/phetsims/area-builder/issues/83 - some were addressed, some weren't. So while I agree with you that there's potential for generalization, I think there's going to be a nontrivial amount of work involved.

**Comment by samreid** [comment]
> Exchange operate is that the former pre-allocates the model elements and puts them in the toolbox, whereas the latter creates the model elements on demand using 'creator nodes'.

I agree, CCK worked very well to have the "creator nodes" pattern and Build a Fraction worked very well to have the "cards are already in the model" pattern.
