### ISSUE TITLE
icons needed for the game screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#50]
We need icons for the game screen. There are eight levels.

**Comment by amanda-phet** [comment]
I think we should do something like this for the icons: 

Levels 1-3 look like "coin values" on coins, and levels 4-8 are on card stacks that increase with each level. I took a screenshot for the card stack, but assume it can be done in code. 

<img width="551" alt="screen shot 2017-03-22 at 2 48 18 pm" src="https://cloud.githubusercontent.com/assets/7852916/24220096/ad352f92-0f0e-11e7-98bf-e5ac76647854.png">

**Comment by jbphet** [comment]
This is implemented, @amanda-phet - please take a look and, if the icons look good, close this issue.

**Comment by jbphet** [comment]
Oops, hang on - I just realized the card stacking direction doesn't match what's in the game.  I'll fix that, then assign back to @amanda-phet.

**Comment by amanda-phet** [comment]
Do we need higher-res images of the coins? They look a bit fuzzy to me.

<img width="582" alt="screen shot 2017-05-04 at 11 51 41 am" src="https://cloud.githubusercontent.com/assets/7852916/25717563/0fb40940-30c0-11e7-88aa-718123660fd4.png">

**Comment by jbphet** [comment]
Yeah, I noticed that too, then thought maybe my eyes were just getting older. :-)  I'll go ahead and create higher res images once the shadows are updated (see #83) and will start using mipmaps for a better appearance at the different resolutions used throughout the sim.

**Comment by jbphet** [comment]
I've updated to higher-res images for the coin terms.  @amanda-phet - please check it out on master and see if you think this cuts it.  I did a side-by-side comparison and I saw a noticeable improvement.

**Comment by amanda-phet** [comment]
Looks great!
