### ISSUE TITLE
Baseline (instead of centers) of cards should be aligned

### ISSUE THREAD

**Issue by samreid** [phetsims/expression-exchange#52]
It would look nicer if the cards were aligned along their baselines instead of centers.  It will help with the stacking analogy and being able to see stack sizes.

![image](https://cloud.githubusercontent.com/assets/679486/22158808/4f5b5358-defb-11e6-8482-7a86880d7fcd.png)

![image](https://cloud.githubusercontent.com/assets/679486/22158823/60ea7b76-defb-11e6-9cc9-ead7f6353ecc.png)

**Comment by amanda-phet** [comment]
Seems like a reasonable idea. I didn't notice the alignment because most piles are similar in size, but in this example they are pretty different. 

@jbphet is it easy to align the stacks so that they are aligned at the top?

**Comment by jbphet** [comment]
I wouldn't say 'easy', but it's certainly possible.  I'll see what I can do.

**Comment by jbphet** [comment]
I've made this change and reviewed it with @amanda-phet, who approved of the new look.  Closing.
