### ISSUE TITLE
test that the challenges were all entered correctly

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#56]
The game screen has 8 levels with 5 challenges each for a total of 40 challenges.  Each challenge has 3 equations that the user needs to construct to complete the challenge, so there are 120 equations.  I've entered all of these into the code, but I did it quickly, and probably didn't get them all right.  I could use some help verifying them.

I've published a version where the order of the challenges is not randomized, so they should match the order in which they are described in the spec, which should make them easier to check.  The spec can be found at https://docs.google.com/document/d/1ppP9pgm0Nc0SEZbPZnrKhhXZ9JKKzurfxg7_Dvbh_rM/edit#, and the challenges are described in the tables in the "Level Overview" section.  Please verify that challenges that are described in this document match those that appear in version http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.19/expression-exchange_en.html of the sim.  The equations and the carousel contents should be verified.

Note that the game cannot be played yet - the collection areas are not yet operational.

EDIT read this to navigate this easier @jbphet and @amanda-phet:

For @jbphet: 
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279467919
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279470903
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279474904

For @amanda-phet:
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279454315
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279459667
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279462829
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279470021
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279472312
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279473300 (unsolvable)
- [x] https://github.com/phetsims/expression-exchange/issues/56#issuecomment-279480592 (unsolvable)

**Comment by phet-steele** [comment]
@jbphet @amanda-phet it's my understanding that level 2 is not yet supposed to have left over terms in the carousel. If that's true the last challenge has one too many "y" terms.

<img width="127" alt="screen shot 2017-02-13 at 10 01 03 am" src="https://cloud.githubusercontent.com/assets/5863899/22893613/6668e084-f1d3-11e6-9a49-161f7ffe907d.png">

The targets add to 4 "y" terms, but there are five in the carousel. Maybe it should be "2{y}, 1{2y}"?

**Comment by phet-steele** [comment]
Same deal in the last challenge of level 4. There are 4 "y<sup>2</sup>" terms in the targets, but 5 in the carousel.
<img width="124" alt="screen shot 2017-02-13 at 10 19 51 am" src="https://cloud.githubusercontent.com/assets/5863899/22894405/1a5c5cae-f1d6-11e6-95a1-53ccaf7ff444.png">

**Comment by phet-steele** [comment]
Level 5, I also could not think of a way to not have left overs in the first challenge. I always had 2{1} left over.

<img width="130" alt="screen shot 2017-02-13 at 10 32 16 am" src="https://cloud.githubusercontent.com/assets/5863899/22894848/b81fe900-f1d7-11e6-9118-ded18f0dd5d0.png">

**Comment by phet-steele** [comment]
@jbphet, third challenge of level five, first target should be "y-2x", not "y-2y".

![screen shot 2017-02-13 at 10 49 49 am](https://cloud.githubusercontent.com/assets/5863899/22895591/4536f246-f1da-11e6-93af-0bf3bae0e1bd.png)
<img width="117" alt="screen shot 2017-02-13 at 10 49 53 am" src="https://cloud.githubusercontent.com/assets/5863899/22895599/49f8785e-f1da-11e6-955f-0ac3287e8507.png">

**Comment by phet-steele** [comment]
@amanda-phet first challenge of level six, I always had some combination leading to -2x being left over (whether it was 1{-2x} or 2{-x})

<img width="117" alt="screen shot 2017-02-13 at 10 57 38 am" src="https://cloud.githubusercontent.com/assets/5863899/22895884/42981334-f1db-11e6-8910-b7abacfb184f.png">

**Comment by phet-steele** [comment]
@jbphet 3rd challenge of level 5, carousel should contain one "-4z", not "-3z".

![screen shot 2017-02-13 at 10 59 40 am](https://cloud.githubusercontent.com/assets/5863899/22895982/a6ea07ac-f1db-11e6-9e30-986527b62338.png)
<img width="118" alt="screen shot 2017-02-13 at 10 59 47 am" src="https://cloud.githubusercontent.com/assets/5863899/22895990/aac8e08c-f1db-11e6-8ab2-758488b21a29.png">

**Comment by phet-steele** [comment]
@amanda-phet the 4th challenge of level 6 is an interesting one. The left over terms equate to 0       (1{y}, 1{-y}). I can go out of my way to use them, but the simplest solution leaves them unused. This one may be okay to not change, but still noting it.

<img width="121" alt="screen shot 2017-02-13 at 11 03 16 am" src="https://cloud.githubusercontent.com/assets/5863899/22896160/40ac31e4-f1dc-11e6-9bbb-ba4e27ad06a1.png">

**Comment by phet-steele** [comment]
@amanda-phet the last challenge in level 6 is my **first** unsolvable prompt. I do not have the 12 "y" terms the targets are asking for, I only have 11.

<img width="129" alt="screen shot 2017-02-13 at 11 07 56 am" src="https://cloud.githubusercontent.com/assets/5863899/22896297/d135121c-f1dc-11e6-8bae-072cb4bad989.png">

**Comment by phet-steele** [comment]
@jbphet 3rd challenge of level 7 wants 2{3}, not 1{3}.

![screen shot 2017-02-13 at 11 13 41 am](https://cloud.githubusercontent.com/assets/5863899/22896492/948b8d4a-f1dd-11e6-86fa-c1216d0cc1de.png)

<img width="131" alt="screen shot 2017-02-13 at 11 14 31 am" src="https://cloud.githubusercontent.com/assets/5863899/22896499/9eef168a-f1dd-11e6-8a58-8977d1902618.png">

**Comment by phet-steele** [comment]
@amanda-phet the 4th challenge of level 8 is unsolvable. I cannot make a positive "2" term for the first target.

![screen shot 2017-02-13 at 11 34 45 am](https://cloud.githubusercontent.com/assets/5863899/22897312/78eb10ee-f1e0-11e6-9719-3b2202551a6d.png)
<img width="116" alt="screen shot 2017-02-13 at 11 34 49 am" src="https://cloud.githubusercontent.com/assets/5863899/22897316/7eba83d8-f1e0-11e6-93d7-d24606512ee8.png">

**Comment by phet-steele** [comment]
@jbphet I've finished and problems are noted in the string of comments above. I'll edit the first post to include a checklist of comments to make this easier to read.

**Comment by jbphet** [comment]
Thanks @phet-steele - that was some very thorough testing.

I've addressed the three data-entry issues that were noted, and will unassign myself until @amanda-phet has addressed the other issues.  At that point, she should assign back to me and I'll implement the changes.

**Comment by amanda-phet** [comment]
Thanks @phet-steele . I wasn't sure how to address the issues here in github but I made changes in the design doc and highlighted them. Assigning to @jbphet to review the changes in the design doc and update the code.

**Comment by jbphet** [comment]
The code has now been updated based on the updates/corrections in the design document.  Assigning back to @phet-steele to run through these again and see if they are all now correct.

**Comment by phet-steele** [comment]
Everything is correct! Thanks @jbphet and @amanda-phet.

**Comment by jbphet** [comment]
Thanks @phet-steele.
