### ISSUE TITLE
should we use the score bar in the game?

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#59]
In today's status meeting while I was demonstrating the game screen for Expression Exchange, @kathy-phet asked if we were going to use the score bar.  I hadn't thought about it, but after looking at it in the Balancing Act simulation, it looks like it would work well and would make this sim more consistent with other sims that include games.  Here's a screenshot:

![baa-game-with-score-bar](https://cloud.githubusercontent.com/assets/3082831/23035467/6e141694-f43c-11e6-8ecd-cd7bfd873fa5.PNG)

Assigning to @amanda-phet to decide if whether I should go ahead and pull this in.

**Comment by amanda-phet** [comment]
This game is pretty different from the games in Balancing Act, Graphing Lines, etc. and is modeled more after Build a Fraction. In the ExEx game, there isn't a series of challenges and there isn't a score, so the bar doesn't seem as appropriate. I'm certainly open to discussing what would go in the bar, but as the game is currently functioning it would basically just state the level and include the back/refresh buttons. 

If @ariel-phet or @kathy-phet have other ideas about how the bar would be used please comment.

**Comment by kathy-phet** [comment]
@amanda-phet - I'm fine with no bar. I see what you say its more like Build a Fraction or Arithmetic.

**Comment by amanda-phet** [comment]
Sounds good. If we want to go this route after interviews prove that something is needed I will re-open the issue.
