### ISSUE TITLE
Sound effects would enhance this simulation

### ISSUE THREAD

**Issue by samreid** [phetsims/expression-exchange#6]
During today's meeting, @jbphet demonstrated the latest expression-exchange. It seems like it would enhance the simulation to add a sound effect for when terms combine and an expression gets larger, and a different sound effect for when an expression gets smaller (if that occurs in the sim).  In some simulations, sound effects may be distracting but here I think they could help students more quickly get a better grasp on the concepts.

**Comment by ariel-phet** [comment]
@amanda-phet seems like a question/consideration for you

**Comment by amanda-phet** [comment]
When more of the sim functionality is implemented I think this is something we could consider. Right now I'm not sure it it helps to achieve the learning goals, but it's certainly worth discussing.

**Comment by amanda-phet** [comment]
After seeing students using this sim in interviews, I don't think a sound effect would have added to what the student was learning in the sim without sound.
