### ISSUE TITLE
Some collection area "coin hints" are not centered

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#61]
2 out of the 3 collection areas in the 1st level that accept a 3 term answer are not centered well.

A bad alignment:
<img width="378" alt="screen shot 2017-03-22 at 4 21 56 pm" src="https://cloud.githubusercontent.com/assets/5863899/24223541/4173bde2-0f1c-11e7-81ee-40edcdfa6df5.png">

A good alignment:
<img width="370" alt="screen shot 2017-03-22 at 4 22 05 pm" src="https://cloud.githubusercontent.com/assets/5863899/24223547/4ba9b730-0f1c-11e7-8487-aa395d9cbe28.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/807.
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.21/expression-exchange_en.html
Version: 1.0.0-dev.21 2017-03-22 20:43:18 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1920x1035
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"27a73346","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"cee4e64f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"expression-exchange":{"sha":"9652db1d","branch":"master"},"joist":{"sha":"7540ec3c","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"02fb8a32","branch":"master"},"scenery-phet":{"sha":"f4fee1ab","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"d98d635a","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by jbphet** [comment]
This was due to using the bounds of the parent node to derive the center position, which were be altered by the addition of the larger hint.  It has been changed to used the actual bounds of the collection area.  Will have this tested in a future version.

**Comment by jbphet** [comment]
This should be fixed, please test on http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.22/expression-exchange_en.html and close if the issue appears to be resolved.

**Comment by phet-steele** [comment]
Resolved, thanks.
