### ISSUE TITLE
You can simultaneously drop terms in the carousel AND answer a challenge

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#62]
The bottom collection area on each challenge is dangerously close to the carousel. This means you can answer a target at the same time as you drop some terms into the carousel:

![ee02](https://cloud.githubusercontent.com/assets/5863899/24223867/aee9eb7a-0f1d-11e7-8016-4ce2a4024eca.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#807.
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.21/expression-exchange_en.html
Version: 1.0.0-dev.21 2017-03-22 20:43:18 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1920x1035
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"27a73346","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"cee4e64f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"expression-exchange":{"sha":"9652db1d","branch":"master"},"joist":{"sha":"7540ec3c","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"02fb8a32","branch":"master"},"scenery-phet":{"sha":"f4fee1ab","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"d98d635a","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by jbphet** [comment]
Fixed, will have this tested on next release.

**Comment by jbphet** [comment]
This should be fixed, please test on http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.22/expression-exchange_en.html and close if the issue appears to be resolved.

**Comment by phet-steele** [comment]
@jbphet @amanda-phet this seems to work great when you are giving the collection area the correct answer. However, when giving the wrong answer, the expression is simply placed into the carousel. Wouldn't it be better to instead reject the wrong answer and animate it to the left of the collection area? (like normal).

The current behaviour, with the wrong answer:
![ee05](https://cloud.githubusercontent.com/assets/5863899/24369072/0f7e67c0-12e0-11e7-86a0-56a7a30a638c.gif)

**Comment by amanda-phet** [comment]
@phet-steele I agree. The collection area is highlighted, making you think that is the target, so a user would probably not expect the expression to go to the panel.

**Comment by phet-steele** [comment]
Now if any expression (right or wrong) is over the carousel, there will not be a halo around the collection area. This makes it very obvious that, upon release, the expression will enter the carousel.
