### ISSUE TITLE
"Next" can be pressed multiple times

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#63]
After answering all challenges in a level, very quickly clicking/tapping "Next" will transition to the next level multiple times. This effectively skips levels.

![ee03](https://cloud.githubusercontent.com/assets/5863899/24272169/ac0c15bc-0fe1-11e7-97c9-da365a059441.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#807.
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.21/expression-exchange_en.html
Version: 1.0.0-dev.21 2017-03-22 20:43:18 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1920x1035
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"27a73346","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"cee4e64f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"expression-exchange":{"sha":"9652db1d","branch":"master"},"joist":{"sha":"7540ec3c","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"02fb8a32","branch":"master"},"scenery-phet":{"sha":"f4fee1ab","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"d98d635a","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by jbphet** [comment]
I've implemented a fix where the `NextLevelNode` is hidden as soon as the user presses its button.  This works well, and I like it.  It has the consequence that if the user returns to that level, the `NextLevelNode` is no longer visible, so the user either has to press the refresh button and play again or go back to the level selection screen.  I actually rather like this behavior since it might get people to play more, but it is not consistent with the behavior of the Build a Fraction simulation.  Assigning to @amanda-phet to decide if this new behavior is okay or if I should come up with something else.

**Comment by jbphet** [comment]
The new behavior is available on version http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.22/expression-exchange_en.html.  @amanda-phet - if you decide that the new behavior is resonable, please assign this to the QA team to verify that it also fully addresses this issue and they can close or reassign as appropriate.

**Comment by amanda-phet** [comment]
I like this new behavior. It is consistent with some other sims like Arithmetic, so I can review my work or refresh to get a new set of challenges.

**Comment by phet-steele** [comment]
The button looks to be working great, thanks.
