### ISSUE TITLE
Screen slide breaks with expressions out of bounds

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#65]
Any expression that is outside of the dev bounds (fully or partially) on a game level affects the position of the "center" of the screen during animations. This can cause the "screen slide" animation to and from a level to be incorrect.

1. Pick a level and assemble all of its terms into a single expression. Longer expressions make this more obvious, but it still occurs with two term expressions.
2. Drag the expression all the way left or right, as far as you can.
3. Go back to the level selection screen.
4. Go back to the level you chose in step 1.

![ee04](https://cloud.githubusercontent.com/assets/5863899/24273021/c2b6b002-0fe5-11e7-8676-b161e954b28e.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#807.
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.21/expression-exchange_en.html
Version: 1.0.0-dev.21 2017-03-22 20:43:18 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1920x1035
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"27a73346","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"cee4e64f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"expression-exchange":{"sha":"9652db1d","branch":"master"},"joist":{"sha":"7540ec3c","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"02fb8a32","branch":"master"},"scenery-phet":{"sha":"f4fee1ab","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"d98d635a","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by EthanWJohnson** [comment]
This bug is worse than that--it also does weird things to the manipulation boxes of expressions in the carousal, making them more off center than the box appears to be. 
![weird boxes](https://cloud.githubusercontent.com/assets/22551096/24314875/85413e26-10a9-11e7-9bfa-6664df2cc5f0.gif)

**Comment by jbphet** [comment]
This was caused by some animations that were positioning screens based on center position values, which take all bounds into account, instead of using just the x and y values for positioning.  Should now be fixed.  Will leave open and have it verified on a future release.

**Comment by jbphet** [comment]
This should be fixed, please test on http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.22/expression-exchange_en.html and close if the issue appears to be resolved.

**Comment by phet-steele** [comment]
Looks fixed, thank @jbphet.
