### ISSUE TITLE
Terms at identical positions can be combined multiple times

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#67]
Start by putting two terms directly on top of each other. This is easiest in a game level:

1. Take a single term and try to use it as an answer in a collection area. It will get rejected and animate to the left.
2. Take a second single term (of the same value as the term in step 1) and attempt to answer the same challenge as in step 1. The term will be rejected and animate left.
3. You now have two identical terms directly over each other.
4. Click on the "stack" of terms without any directional movement of your cursor, the terms need to remain on top of each other. Click as many time as you want and notice the terms are not combining.
5. When you are satisfied with your clicking, click and drag the top term away from the bottom term, then drag it back onto the bottom term (the video below shows this only needs to be a slight directional movement). Do NOT drag the bottom term to the top term.
6. You will now have a large combined count (noted by the coefficient) based on how many clicks you made in step 4.

This IS possible on the other three screens and requires combining terms in a corner of the screen (to ensure two terms are on top of each other). By dragging past the corner of the screen, the term you are dragging will be confined to the sim bounds and be placed at a specific location.
 
Everything in this issue happens to both coins and variables, and to terms with a preset combined count.

Procedure in game (I clicked a lot and edited most of the clicking out):
![ee06](https://cloud.githubusercontent.com/assets/5863899/24379322/d8e55bc8-1303-11e7-903a-5f50c7b524a3.gif)

"Corner Screen" procedure:
![ee07](https://cloud.githubusercontent.com/assets/5863899/24379413/2dbeae9c-1304-11e7-8d31-1ae6ceab7899.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#807.
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.22/expression-exchange_en.html
Version: 1.0.0-dev.22 2017-03-24 23:46:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1497x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"ca937302","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"a3f44a2f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"expression-exchange":{"sha":"3ed2a67f","branch":"master"},"joist":{"sha":"e9e4056a","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"e24681a5","branch":"master"},"scenery-phet":{"sha":"e404e619","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"28d0127c","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by amanda-phet** [comment]
While I didn't see any students do this during interviews, I did see them try to drop terms in the collection box and they would overlap so perfectly it might have caused a moment of confusion.

**Comment by jbphet** [comment]
I have fixed the primary issue described, but I didn't address the overlap problem mentioned by @amanda-phet in the comment immediately above.  Assigning to @amanda-phet - if she thinks that the overlap is an problem, a separate GitHub issue should be logged.  After that, this issue should be unassigned and I'll put it on the list to get verified during the next round of testing.

**Comment by amanda-phet** [comment]
I can't think of a great fix for the overlap issue, and it wasn't a huge problem in interviews, so I will not open another github issue.

**Comment by phet-steele** [comment]
Primary issue fixed, closing.
