### ISSUE TITLE
?stringTest=double issues

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#68]
<img width="1379" alt="screen shot 2017-03-28 at 12 08 07 pm" src="https://cloud.githubusercontent.com/assets/5863899/24420194/41761258-13af-11e7-94af-67995669b7c0.png">

1. Total panel is unnecessarily large
2. Values and My Collection panel title overlaps with the expand/collapse button
3. Checkboxes overlap with the carousel (not an obvious problem on the first screen)

Issues are generally shared with the first three screens. The game screen is not negatively affected by this stringTest.

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#807.
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.22/expression-exchange_en.html
Version: 1.0.0-dev.22 2017-03-24 23:46:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
Language: en-US
Window: 1497x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"ca937302","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"a3f44a2f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"expression-exchange":{"sha":"3ed2a67f","branch":"master"},"joist":{"sha":"e9e4056a","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"e24681a5","branch":"master"},"scenery-phet":{"sha":"e404e619","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"28d0127c","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by jbphet** [comment]
These should now be resolved, closing (since this will be retested during release process).

**Comment by phet-steele** [comment]
Point two is still an issue in 1.1.0-rc.1:

> Values and My Collection panel title overlaps with the expand/collapse button

**Comment by jbphet** [comment]
Added explicit width limits to the titles.

**Comment by phet-steele** [comment]
1.1.0-rc.2 passes.
