### ISSUE TITLE
add reward screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#71]
There should be a reward screen that is shown after all levels are completed.

**Comment by amanda-phet** [comment]
Adding a note: it shouldn't matter which level was completed last.

**Comment by jbphet** [comment]
This should be done, unassigning for now and will assign back to someone for testing on next dev release.

**Comment by jbphet** [comment]
For testing purposes, I've added a query param to show the reward node at the completion of every level.  The flag is `showRewardNodeEveryLevel`.

**Comment by phet-steele** [comment]
The RewardNode is working great!
