### ISSUE TITLE
Show "next level" button after a level is completed

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/expression-exchange#73]
In an interview, a student completed level 4 first, then decided to go back to level 1. 
<img width="881" alt="screen shot 2017-04-05 at 11 52 19 am" src="https://cloud.githubusercontent.com/assets/7852916/24719260/5a0ddc36-19f6-11e7-9dc9-a8805bb6b07d.png">

She completed levels 1,2,3, and when she arrived at level 4 there was no option to move to the next level. 
<img width="887" alt="screen shot 2017-04-05 at 11 50 45 am" src="https://cloud.githubusercontent.com/assets/7852916/24719209/285f5c5a-19f6-11e7-931b-673636b8db6d.png">

She clicked the back button and then clicked level 5, which didn't seem to throw her off too much, but another student had a similar interaction on level 8 (which he completed first) and when he arrived at it he said "did I do something wrong?" 

It seems like good user interaction to have a next button appear again so that the user can flow easily through all levels.

**Comment by jbphet** [comment]
I've changed the code to keep the 'Next' dialog up whenever a level is complete, and added to to prevent interaction while animations are in progress to avoid the problem described in https://github.com/phetsims/expression-exchange/issues/63.  This seems to work pretty well, assigning to @amanda-phet to verify on master and close if the behavior seems reasonable.

**Comment by amanda-phet** [comment]
Looks great to me. Thanks!
