### ISSUE TITLE
Terms can be dropped into the carousel while editing an expression

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#74]
@jbphet a recent change did this, as the issue is not in dev.22 (probably https://github.com/phetsims/expression-exchange/commit/ad7bc82a3a2932637f734f80db405ee23331e50e).

![ee09](https://cloud.githubusercontent.com/assets/5863899/24727501/7855fd8c-1a13-11e7-855b-a821112e8cbe.gif)

**Comment by jbphet** [comment]
Should now be fixed, @phet-steele please verify on master.

**Comment by phet-steele** [comment]
Fixed, thanks.
