### ISSUE TITLE
Changes to levels 1-3

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/expression-exchange#75]
Based on the game flow I observed in interviews, I am suggesting that we make changes to levels 1-3. What I noticed is that students figured out the cues quite easily and learned to simplify their answers. When they got to levels 4-8 students continue to simplify their answers even though they didn't need to. However, I'd like students to know they can leave the answer unsimplified, and see that their answer might not look identical to the target but it is still equivalent. One way of resolving this is by changing levels 1-3. 

Decided in 4/13/17 design meeting to make the following changes to levels 1-3. (¢ = coin image)

- Targets will be "expressions" instead of "collections." (ex: target will read 5¢ instead of ¢¢¢¢¢)
- The targets will NOT have dotted circle cues anymore
- Answers do NOT need to be simplified to be correct (ex: 3(¢)+2(¢) is considered correct, along with 5(¢)) 

Here is another example comparing the current sim appearance and the new appearance. 

<img width="664" alt="screen shot 2017-04-11 at 1 05 51 pm" src="https://cloud.githubusercontent.com/assets/7852916/24926089/a5c3fbcc-1eb7-11e7-8145-4f1996ba2347.png">

**Comment by jbphet** [comment]
This has been implemented on the master branch, assigning to @amanda-phet to test and close if the new behavior looks good.

**Comment by amanda-phet** [comment]
Look great. Thanks!
