### ISSUE TITLE
Change edit icon

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/expression-exchange#76]
In the 4/6/17 design meeting we decided we like the appearance of the fontawesome "exchange" icon instead of the current icon being used for editing an expression. 

<img width="194" alt="screen shot 2017-04-11 at 1 12 37 pm" src="https://cloud.githubusercontent.com/assets/7852916/24926361/8fd8dde0-1eb8-11e7-91ed-8e584388a2a5.png">

**Comment by jbphet** [comment]
Done.  Will assign to someone to verify on next dev release.

**Comment by amanda-phet** [comment]
This has been fixed for a while and I confirmed it looks great. Closing.
