### ISSUE TITLE
Terms seem to be entering the carousel too easily

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#78]
@amanda-phet recent versions of this sim have (probably unintentionally) increased the "drop-in-the-carousel" range. For example in dev.22, if I release a coin at this distance it will drop into the carousel:
<img width="867" alt="screen shot 2017-04-13 at 10 39 22 am" src="https://cloud.githubusercontent.com/assets/5863899/25014576/96f36c66-2035-11e7-91e8-33fb16408d9e.png">

Whereas in an older version, like dev.18, you have to be touching the carousel to drop it in:
<img width="890" alt="screen shot 2017-04-13 at 10 41 17 am" src="https://cloud.githubusercontent.com/assets/5863899/25014626/c81f4fc6-2035-11e7-9b4f-29123d869b83.png">

Is this a UX issue? It might be annoying to have things return to the carousel so easily. Maybe @jbphet should look into why this is first, then we can gauge the importance of this issue on the work it would take to change it. This affects all screens and terms.

For phetsims/tasks/issues/807.

**Comment by amanda-phet** [comment]
I'm not seeing this in the latest on phettest... perhaps it got fixed? It is definitely not intentional or related to the design. @jbphet can you investigate this, if it's still happening, and what caused it?

**Comment by phet-steele** [comment]
@jbphet I too no longer see this in master. You've done a lot of logic changes since dev.22, good chance this was fixed.

**Comment by jbphet** [comment]
I just tested on master and it's looking good.  Closing.
