### ISSUE TITLE
Anchor expressions can be collected before they finish being combined with the incoming expression

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#79]
In a game level:
1. Create the correct answer and place it near the corresponding collection area.
2. Create a second, totally bogus, expression. The longer the better.
3. Read this and the next step before doing either. Drag the second expression and combine it with the first.
4. BEFORE the second expression has successfully combined, drag the first expression into the collection area. It will be the correct answer and will be "collected".
5. The second expression will then combine to the first:
![ee10](https://cloud.githubusercontent.com/assets/5863899/25015353/a8fa8bf8-2038-11e7-8754-286e2f23bd2e.gif)

Seen on macOS 10.12.4 Chrome, for phetsims/tasks/issues/807.
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.22/expression-exchange_en.html
Version: 1.0.0-dev.22 2017-03-24 23:46:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"master"},"axon":{"sha":"f7720d0e","branch":"master"},"babel":{"sha":"ca937302","branch":"master"},"brand":{"sha":"0be722ee","branch":"master"},"chipper":{"sha":"a3f44a2f","branch":"master"},"dot":{"sha":"569939e1","branch":"master"},"expression-exchange":{"sha":"3ed2a67f","branch":"master"},"joist":{"sha":"e9e4056a","branch":"master"},"kite":{"sha":"81166ce9","branch":"master"},"phet-core":{"sha":"c5c6c2a8","branch":"master"},"phetcommon":{"sha":"c7cb85b6","branch":"master"},"query-string-machine":{"sha":"d8a4ff18","branch":"master"},"scenery":{"sha":"e24681a5","branch":"master"},"scenery-phet":{"sha":"e404e619","branch":"master"},"sherpa":{"sha":"3255de0f","branch":"master"},"sun":{"sha":"28d0127c","branch":"master"},"tandem":{"sha":"a668abd5","branch":"master"},"vegas":{"sha":"1e2b1b0c","branch":"master"},"vibe":{"sha":"549baf54","branch":"master"}}

**Comment by jbphet** [comment]
I added code that waives off on combining two expressions if the destination expression has moved by the time the combining expression reaches its edge.  This addresses the problem, but might have other adverse effects.  Assigning to @phet-steele to test on master.

**Comment by jbphet** [comment]
Unassigning since QA is backed up, will have on the list of issues to test against the first RC for this sim, which should be soon.

**Comment by phet-steele** [comment]
@jbphet I haven't been able to reproduce in 1.1.0-dev.3.
