### ISSUE TITLE
incorrect lighting for coins

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#83]
Noted while working on equality-explorer, which has some similarities. 

The lighting on the coins is incorrect. PhET light source is above-left. The coins are lit from below-left.

![screenshot_239](https://cloud.githubusercontent.com/assets/3046552/25628522/b854222c-2f23-11e7-9279-374906059d34.png)

**Comment by amanda-phet** [comment]
Is light source the same as perspective, in this situation? The coins don't have highlights, but we are trying to give them depth. Should we modify the perspective to match our typical light source direction?

**Comment by pixelzoom** [comment]
Light source _gives_ perspective.  Rotate the visible edge of the coins 90 degrees and it'll be consistent.

**Comment by amanda-phet** [comment]
Done via the following commits: 

https://github.com/phetsims/expression-exchange/commit/a2c2c86ca754c92e73e486771cf53d2295f9dadb

https://github.com/phetsims/expression-exchange/commit/0d4a3f525f0b916ee603b7992650646da56d460e

https://github.com/phetsims/expression-exchange/commit/b68920b26bc4053241fbd9507f4dfbbe350af226
