### ISSUE TITLE
Add some space between the game targets

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/expression-exchange#86]
Before and after:
<img width="432" alt="screen shot 2017-05-04 at 10 33 33 am" src="https://cloud.githubusercontent.com/assets/7852916/25714457/4ed45a9a-30b5-11e7-8e09-9f7d5284f223.png">

**Comment by jbphet** [comment]
I've done the adjustements.  @amanda-phet - please take a look and see what you think, and close if we're done.

**Comment by amanda-phet** [comment]
Looks great to me!
