### ISSUE TITLE
Background color of sim

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/expression-exchange#87]
#84 made me double-check the green background of the sim.. thinking we could change it to coordinate with the nice-looking dark green buttons @pixelzoom suggested. I noticed that the green in the sim doesn't look like the green in the mockups, so, I'm calling on opinions regarding the background color.

(1) is what my browser picked up as the current sim color
(2) is what I had in my original mockups
(3) is a new color with less blue in it that could go well with dark green game level buttons. 

@jbphet @pixelzoom @ariel-phet @kathy-phet @phet-steele Any opinions?  

<img width="264" alt="screen shot 2017-05-09 at 1 44 43 pm" src="https://cloud.githubusercontent.com/assets/7852916/25869527/db727fca-34bd-11e7-9da4-fbe491672664.png">

**Comment by pixelzoom** [comment]
Either 1 or 2 look good to me.  I don't like 3, a bit too yellow, looks a little sickly.

**Comment by kathy-phet** [comment]
I feel like 2 doesn't have a good enough contrast with the gray coins. So I prefer 1 over 2.

Sent from my iPhone

On May 9, 2017, at 1:53 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


Either 1 or 2 look good to me. I don't like 3, a bit too yellow, looks a little sickly.

**Comment by jbphet** [comment]
1 or 2 look fine to me, and since @kathy-phet said 1, I can just plan on that.  Which, I think, means leaving it as it currently is in master, right?

**Comment by ariel-phet** [comment]
Sounds good to me

**Comment by amanda-phet** [comment]
Yes that's correct. Thanks for the input everyone.
