### ISSUE TITLE
issues with Values accordion box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/expression-exchange#89]
Related to #88 code review. 

While playing with the sim to familiarize myself with it, I noticed this accordion box:

![screenshot_260](https://cloud.githubusercontent.com/assets/3046552/26068450/d32d2788-395a-11e7-93a4-aec3642d866d.png)

The "Values" accordion box is used to change the values of the variables.  A couple of inconsistencies with the design of other PhET sims:

(1) In Equality Explorer, an similar panel is titled "Variable".  That panel only changes 1 variable, but the idea is the same - it's a control used to determine the values of variables.

(2) Pressing the button in this panel resets the values to their initial values.  So it would be more appropriate to use a ResetButton.  Instead, it's using a button with a "refresh" icon, which is typically used to generate a new set of random values, or the next value in a sequence of choices. See for example: the Mystery screen in Function Builder; the Questions panel in Unit Rates; any of the screens in Arithmetic; and even the Game screen in Expression Exchange.

To be consistent with other PhET sims, here's what I believe this panel should look like:

![screenshot_261](https://cloud.githubusercontent.com/assets/3046552/26068841/1f87dc1c-395c-11e7-8a00-37c6e644c61e.png)

Assigning to @amanda-phet since she's lead designer.

**Comment by amanda-phet** [comment]
(1) In ExEx we use the term "value" in a few places, such as "coin values" and "variable values", so I'd prefer "variable values" for this panel, but that's quite a long title. I don't love calling it "variables", but am ok with it, especially if there is a similar panel in another sim. 

(2) I agree, @pixelzoom . This white reset button is relatively new to me but seems to be popular in new sims, so let's definitely change the button.

**Comment by amanda-phet** [comment]
@jbphet feel free to weigh in on (1) but I'm confident about the change in (2).

**Comment by pixelzoom** [comment]
"Values" also seems a bit vague/ambiguous.  There are other "values" in the sim - the total, values and coefficients shown in carousels,...  And you have a check box labeled "variable values", which seems related to the "Values" accordion box.

**Comment by jbphet** [comment]
I've gone ahead with adding the pale looking reset button.

As for the caption, "Variable Values" would be ideal, but it's a bit big for this accordion box.  For the heck of it, I tried it and it looked like this:
![exex-values](https://cloud.githubusercontent.com/assets/3082831/26222010/a6addffe-3bd5-11e7-933f-8425136ac133.PNG)

I thought about it for a bit, and I think "Values" is a reasonable choice.  It may not be instantly obvious, but as soon as a user opens the box they will see that it is the values of the *variables* that they have the opportunity to control.  So I'm inclined to stick with "Values".

Back to @amanda-phet for the final call.

**Comment by amanda-phet** [comment]
I think I prefer "Variables" because it is stating information about the variables, and **not** the coins, so that distinction is important in this sim. And while they will see this right away, it is also a nice cue about what to expect. Also, Trig Tour has a "values" panel that is pretty different- it is simply a readout. 

So, please go ahead and change it to "Variables."

**Comment by jbphet** [comment]
Done, it now looks like this:
![exex-panel](https://cloud.githubusercontent.com/assets/3082831/26471425/d491cc9e-415e-11e7-9432-276ed5258bbd.PNG)
Back to you @amanda-phet, please close if it looks okay.

**Comment by amanda-phet** [comment]
Looks good. Thanks.
