### ISSUE TITLE
What is the purpose of my-collection.ai?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/expression-exchange#94]
Looks like coin-artwork.ai includes all of the required assets?

For the code review https://github.com/phetsims/expression-exchange/issues/88

**Comment by jbphet** [comment]
Good catch.  This is no longer needed - it was originally for the small versions of the coins that were going to be used in the "My Collection" display, but I ended up generating those programmatically.  I've removed the file.  Closing.
