### ISSUE TITLE
Ensure credits are correct before publication

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/expression-exchange#95]
Including QA. Issue mentioned in code review doc, but will be completed afterwards.

**Comment by jbphet** [comment]
@phet-steele - who should be on QA credits?
@ariel-phet - there is some artwork for the coins - should that be credited and, if so, to whom?

**Comment by jbphet** [comment]
Please assign back to me when both questions are answered.

**Comment by ariel-phet** [comment]
@jbphet coins were done by Mariah

**Comment by amanda-phet** [comment]
David Webb needs to be added to the team.

**Comment by amanda-phet** [comment]
Can you also remove me from the team since I'm already listed as lead? I just checked a few sims and the lead is not usually listed twice.

**Comment by jbphet** [comment]
I hadn't noticed the redundant entry - that has been fixed.  I also added David Webb.

**Comment by phet-steele** [comment]
@jbphet the QA credits are good. Doubt they will change in 1.1.0-rc.2.
