### ISSUE TITLE
Simulation version?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/expression-exchange#96]
Looks like there's a 1.0-phetio branch, with 1.0.1 published. That would imply we would start off with 1.0.2 as a version for the main sim when it is visible?

Is Expression Exchange currently a live phet-io sim?

For the code review https://github.com/phetsims/expression-exchange/issues/88

**Comment by jbphet** [comment]
An early version that included phet-io was released in support of a study, see #57.  This excluded the game.  As a result, we should probably start with a new branch when this release process starts, and the branch name should be 1.1.  Back to you @jonathanolson to say whether you have concerns or objections, and for closure if this sounds okay.

**Comment by jonathanolson** [comment]
I recommend changing to 1.1.0-dev.1 then in package.json?

**Comment by jbphet** [comment]
Ah, an excellent point.  I've done this in 5453745fd7a660a9b70e3cb749233235dead45ec.  Tagging @phet-steele and @amanda-phet so that they are aware that the version numbers have been updated in this way, since it will affect upcoming dev and RC releases.

**Comment by jbphet** [comment]
Version number is now corrected, closing.
