### ISSUE TITLE
artwork for the Y coin appears to have faded in color

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#97]
The current master version of the sim contains a Y coin that looks faded versus previous values.

Here is the carousel in v1.0.0-dev.23 (the center coin is the Y coin):
![exex-darker-coin](https://cloud.githubusercontent.com/assets/3082831/26515902/a244e85a-423c-11e7-8eab-b2de785c7b75.PNG)

This is from the current master version:
![exex-lighter-coin](https://cloud.githubusercontent.com/assets/3082831/26515905/a98b151c-423c-11e7-8ae0-7ea42dc2225c.PNG)

I haven't intentionally changed the appearance of this coin, but I did update the artwork recently in order to get some higher res images.  @amanda-phet - did you change this in the Illustrator?  If so, I think the darker version worked better.  If you can update it in the main asset file, I will pull it into the sim.

**Comment by amanda-phet** [comment]
I updated the assets recently when we changed the perspective. Maybe I was working off an old ai version. I remember now that we darkened the coin at one point so I'll make this change now.

**Comment by amanda-phet** [comment]
Sorry about that. I updated the .ai file and uploaded two exported .png files with the darker coin background. Should be fine now. @jbphet want to verify and close if it all looks good?

**Comment by jbphet** [comment]
Much better - thanks.  Closing.
