### ISSUE TITLE
reset all button overlaps with a checkbox

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#99]
While cleaning up the code for release, the width of the "My Collection" display got reduced, and ended up affecting the layout a bit.  Here is what it looks like on master at the moment, and I need to remember to fix it:
![exex-reset-pos](https://cloud.githubusercontent.com/assets/3082831/26804075/f0cfd682-4a03-11e7-9f51-963416293e55.PNG)

**Comment by jbphet** [comment]
I adjusted the layout, it now looks like this (layout bounds are shown as red lines):
![exex-reset](https://user-images.githubusercontent.com/3082831/26997745-71b0f064-4d39-11e7-8465-e7e1ea90c9e9.PNG)

**Comment by amanda-phet** [comment]
This solution looks good to me. Thanks for fixing the layout!
